name: 66666
url: 77777
spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/
    data-password: null
  cache:
    type: redis
  redis:
    host: 127.0.0.1
    port: 6379
server:
  port: 8080
  context-path: /
  session:
    timeout: 1800
