spring:
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:mysql://127.0.0.1:3306/test
    username: root
    password: root
    hikari:
      minimum-idle: 3
      auto-commit: true
      idle-timeout: 10000
      pool-name: DatebookHikariCP
      max-lifetime: 1800000
      connection-timeout: 30000
  cache:
    type: redis
  redis:
    host: 127.0.0.1
    port: 6379
  output:
    ansi:
      enabled: always
  data:
    solr:
      host: http://127.0.0.1:8080/solr
      repositories:
            enabled: true
  mvc:
    view:
      prefix: /
      suffix: .html
  resources:
    static-locations: classpath:/static
server:
  port: 8080
  context-path: /
  session:
    timeout: 1800
pagehelper:
  helperDialect: mysql
  offsetAsPageNum: true
  rowBoundsWithCount: true
  reasonable: false